src/Patches/TunicPortals.cs

I thought you could go backwards with just laurels, but you trigger the double admin fight along the way which drops the bridge, and you can't laurels across that bridge.
Adds sword and prayer requirement (since you need prayer to bring the bridge back up)

Fix for zig3 er rule

---

src/Patches/TunicPortals.cs

Statue teleporter and portal pad were in the same region for convenience. This was not a great idea, as if you had access to one, it assumed you had access to the other, regardless of whether you have prayer.
Splits them into separate regions.

Fix atoll regions

---

src/Patches/TunicPortals.cs

Make it so with fewer shops on, it only has 1 shop instead of 2.
It was 2 before because I couldn't figure out a satisfying way to make it so there's only 1.
And now, I'm pretty satisfied with just shuffling the zig skip exit into the pool with fewer shops on.

Make Fewer Shops have even fewer shops

---

src/Data/ItemListJson.cs

Gauntlet now requires the wand too, making it match the logic in Archipelago.
The lantern location now requires the stick, since the Well already requires it.

Update logic for lantern location and gauntlet

---

src/Data/Check.cs
src/Data/ItemListJson.cs
src/Patches/ItemRandomizer.cs
src/Patches/TunicPortals.cs

Adds the new regions that ladder shuffle uses.
Partially implements ladder shuffle support, but not all the way, since I'm not sure what you want for the option and such or how to like, turn on making the ladders not show up.

Update ER to add the ladder regions

---

src/Data/RandomizerSettings.cs
src/Patches/QuickSettings.cs

Moves the copy thing to only happen when you click on copy seed and settings.

Make it so the setting string doesn't automatically copy to your clipboard on new game

---

src/Patches/ModelSwaps.cs
src/Patches/TunicPortals.cs

Just purely adds another attribute to the portals to designate which direction they are. Might use this later, might not, but I already regretted not merging this in to the previous PR, so I don't want another messy merge conflict later.

Add directions to portals

---

src/Archipelago/ArchipelagoIntegration.cs
src/Data/Hints.cs
src/Patches/ItemRandomizer.cs
src/Patches/PlayerCharacterPatches.cs

- Allow ladders to be part of first steps items in single player ladder shuffle (if/until you remove first steps from ladder shuffle)
- Properly separate `SphereZero` and `PrecollectedItems` from each other.
- `PrecollectedItems` just contains items you're assumed to have (sword if start with sword is on, ladders if ladder shuffle is off, abilities if ability shuffle is off, lantern/mask if lanternless/maskless are on).
- `SphereZero` will only be populated at the end of gen, and will contain your `PrecollectedItems` as well as the regions you can access with only those items.
- Actually add the ladders to `ProgressionNames` if ladder shuffle is on, which is probably the actual reason why we were getting that hang from "too few places to place items" -- it was likely assuming you had no …

Modifications to the ladders branch

---

README.md
src/Data/RandomizerSettings.cs
src/Patches/EnemyRandomizer.cs
src/Patches/OptionsGUIPatches.cs

- Added toggles for every enemy, allowing you to choose what enemies are able to spawn when the enemy randomizer is on
- If every enemy is toggled off, no enemies will spawn
- Added the enemy toggle settings to the copy/paste settings string

Implement enemy toggles for the enemy randomizer

---

TunicRandomizer.csproj
src/Data/RandomizerSettings.cs
src/Patches/EnemyRandomizer.cs
src/Patches/InteractionPatches.cs
src/Patches/MusicShuffler.cs
src/Patches/OptionsGUIPatches.cs
src/Patches/PlayerCharacterPatches.cs
src/TunicRandomizer.cs

Adds a music shuffle option to the randomizer.
Plays a random music track upon entering a scene, with an option for it to be seeded per scene.
Includes a menu to toggle which tracks get to play, as well as a jukebox/sound test menu to play any track on demand.
Some songs are probably missing, including all nighttime tracks.

Music shuffle feature

---

src/Data/SaveFlags.cs
src/Patches/ItemRandomizer.cs

With the revised fill system, the generator "picks up" items in accessible locations with its current inventory, and keeps doing this until it gets no new items.
To do this, it checks which locations have already been placed, and if it is accessible, picks up its item. Unfortunately, we were not caching which locations were already picked up, so each iteration it would just keep picking up the same locations.
What this PR does:
- Makes a list to cache which locations have been picked up to avoid the bug.
- Revises the counter so that instead of counting how many keys are in the dictionary, it sums the values. So if you have 2 coins, then the next iteration you pick up 1 coin, it will do another iteration instead of stopping.
- If one of the laurels plando options is chosen, it adds the …

Fix the logic bug

---

src/Data/ItemListJson.cs

Updates the logic so you require either a sword or both wand and laurels. While you can get it with just laurels, you will then be unable to get through the rest of upper zig. While I could make it so the rule is different in ER, I'm not gonna because that requires some fake item to say ER is on, and I'm not gonna do that for an alt rule for one check

Update upper zig first chest logic

---

src/Data/ItemListJson.cs
src/Patches/TunicPortals.cs

Need both keys to access either door
Move ice slime check to lower forest, remove connection from upper to lower forest via ice grapple (since it was unpopular in AP)
Remove or comment out some unnecessary connections

Add a few comments, fix key bug

---

src/Data/ItemListJson.cs
src/Patches/TunicPortals.cs

Since the rando moved to the region-like-system in TunicPortals, the sword/wand requirements for getting to checks in Quarry were covered by the region access conditions -- any region-region connections from somewhere to "Quarry" require either the Sword or Wand.
However, the ItemListJson appears to still have the old Sword rule, so basically it's checking if you have:
- Access to Quarry (requiring Sword or Wand and a region adjacent to Quarry)
- A Sword
when it shouldn't have that sword requirement there (since it already checks your weapon requirement earlier)
Also add the Ladders in Library or Laurels requirement for getting from the Library portal pad to the Library lab

Fix quarry and library requirements

---

src/Data/Portal.cs
src/Data/PortalCombo.cs
src/Patches/TunicPortals.cs

If the entrance to a shop is east or south (meaning you walk east or walk south to enter it), it will now have its flipped orientation.

Make shop orientation match entrance orientation in ER

---

src/Patches/ItemPatches.cs

With that newer thing to make upgrades not go up in price if you get free upgrades, the potion upgrades didn't get the correct numbers since they have a weird price jump.
First potion upgrade costs 100, second is 300, third is 1000, fourth and higher and +200 each over the third.
But with the mod, currently if you get 2 free upgrades, your first potion upgrade (to get to level 4) costs 600, which is 500 more than it should be.

Fix potion cost

---

src/Data/Check.cs

idk why this break was here, probably used to be important, but now it just gets out of the loop too early.

Fix Check.reachable

---

src/Data/GrassReqs.json
src/Data/ItemListJson.cs
src/Patches/ERData.cs

Fix some grass in the Swamp incorrectly not requiring Laurels.
Fix a couple region connections in the Library Lab, which I don't actually think create a logic bug, but it's clearly not written correctly so it's fixed now.
Also add logic for the glass page prisons in the library (stick, gun, or wand)
Also add logic for the leaf piles in Dusty (stick or dagger)

Fix a couple logic bugs

---

src/Patches/ERData.cs

Simple reorder of the portal list.
This puts it in the game's general progression order (Overworld -> Forest -> Well -> Dark Tomb -> West Garden -> Fortress -> Atoll -> Quarry -> Swamp and then Far Shore stuff all at the end)
Makes it easier for me to scroll through it, and makes it show a better spoiler output order.
There are no changes other than reordering.

Reorder portal list

---

src/Patches/PlayerCharacterPatches.cs

Ice grappling down from the pillars in swamp to main swamp without the ladder to swamp is a softlock if you don't have laurels zips on. I say screw it, let's just give them the torch to make our lives easier.

Give torch on any ice grappling option

---

src/Patches/ERData.cs
src/Patches/ERScripts.cs
src/Patches/ItemRandomizer.cs
src/Patches/PlayerCharacterPatches.cs
src/Patches/QuickSettings.cs
src/Patches/SceneLoaderPatches.cs

It was checking RandomizedPortals, which was being cleared when you aren't in entrance rando instead of set to VanillaPortals

Fix seeking spell logic for entrance seeking in a scene that has checks left that you can't get to

---

src/Patches/ERData.cs

Making the change on the AP side since I think it's sensible enough

Require sword or wand for Monastery Front -> Back

---

src/Patches/FairyTargets.cs

Sometimes, probably when changing over to looking at adjacent scenes, it would find a portal that leads you to the current scene, and that's dumb, so now it doesn't.

Fix slight fairy target bug
