silent-destroyer/tunic-randomizer

- src/Data/ItemListJson.cs
- src/Models/Location.cs
- src/Models/Portal.cs
- src/Models/PortalCombo.cs
- src/Patches/GhostHints.cs
- src/Patches/ItemRandomizer.cs
- src/Patches/TunicPortals.cs
In ER, first steps is now only shows areas accessible directly from entrances in Overworld (or Overworld itself).
Also a couple of minor logic bugs fixed that were discovered in testing this.
> Better ER first steps, a couple logic fixes

- src/Patches/ItemPatches.cs
- src/Patches/ItemRandomizer.cs
- src/Patches/PlayerCharacterPatches.cs
- src/Patches/SceneLoaderPatches.cs
- src/Patches/TunicPortals.cs
Also fix for the gold hex hints at hero graves
> Made hero grave candles go on when you find its item

- src/Patches/GhostHints.cs
- src/Patches/ItemRandomizer.cs
- src/Patches/ModelSwaps.cs
- src/Patches/SceneLoaderPatches.cs
> Add new hint fox at the East Forest well

- src/Patches/TunicPortals.cs
Now it doesn't populate all of them at once
> Fix for shop portals in entrance log

- src/Data/Portal.cs
- src/Patches/TunicPortals.cs
Starting stuff out here, just making it a draft to make it known what I am doing.
Also minor refactoring on a part because it was confusing to look at.
> Vanilla portals function

- src/Patches/ItemRandomizer.cs
- src/Patches/PlayerCharacterPatches.cs
- src/Patches/SceneLoaderPatches.cs
- src/Patches/TunicPortals.cs
ER first steps was looking at too many places. Now it works properly!
I also refactored a few things
> Fix ER first steps

- src/Patches/EnemyRandomizer.cs
Managed to get the hitreceiver on it. Trying to figure out how to actually make the hit receiver do anything useful.
> Attempting to fix the big crab explosion issue

- src/Patches/EnemyRandomizer.cs
Some extra stuff was left in, presumably for the previous big crab methods
> Clean up after the crabs

- src/Patches/GhostHints.cs
> New hint ghost in Mountain

- src/Archipelago/Archipelago.cs
- src/PluginInfo.cs
- src/Util/Notifications.cs
gotta say, I don't like how .Replace doesn't modify the string, and instead creates a new string
> Fix that brace issue

- src/Data/Check.cs
- src/Data/ItemListJson.cs
- src/Data/ItemTracker.cs
- src/Patches/ItemRandomizer.cs
- src/Patches/TunicPortals.cs
Created a thing to test whether all locations are reachable with a full inventory with the current settings.
To use it, at the top of ItemRandomizer, set testLocations to true
Also fixed a bunch of bugs as a result of using the testing thing
> Create testing stuff, also fix some bugs as a result of testing stuff

- src/Data/Hints.cs
Not that I think anyone actually turns sword progression off lol
> Make it so first steps hint won't hint stick or sword if you have start with sword and no sword progression

- TunicRandomizer.csproj
- packages.config
- src/Archipelago/Archipelago.cs
- src/Archipelago/ArchipelagoIntegration.cs
- src/Data/Hints.cs
- src/Data/ItemTracker.cs
- src/Data/Items.cs
- src/Patches/GhostHints.cs
- src/Patches/InteractionPatches.cs
- src/Patches/ItemPatches.cs
- src/Patches/ModelSwaps.cs
- src/Patches/PlayerCharacterPatches.cs
This is mostly just a quick bandaid fix for now to make the mod work with the new multiclient version. At some point I'll get around to refactoring the rest of the mod to actually use the new stuff in the library but for now the mod should work as it did before.
> Initial compatibility changes to work with Archipelago.MultiClient.Net 6.0.0

- src/Patches/ItemRandomizer.cs
Update fill to assume you have access to items you can reach with your unplaced inventory
> Fill update

- src/Patches/PlayerCharacterPatches.cs
The ToString might be dumb, but I want to believe we didn't check the int for a good reason before
> Add checks for new logic options to see if you get torch

- TunicRandomizer.csproj
- src/Archipelago/Archipelago.cs
- src/Archipelago/ArchipelagoIntegration.cs
- src/Data/Hints.cs
- src/Data/ItemListJson.cs
- src/Data/RandomizerSettings.cs
- src/Patches/FairyTargets.cs
- src/Patches/GhostHints.cs
- src/Patches/ItemPatches.cs
- src/Patches/ItemRandomizer.cs
- src/Patches/OptionsGUIPatches.cs
- src/Patches/PlayerCharacterPatches.cs
- src/Patches/SceneLoaderPatches.cs
- src/Patches/TunicPortals.cs
- src/Util/TunicUtils.cs
Fairy Seeking spell (and entrance seeking spell) can now abide by what is in logic.
Also, I moved a few functions to a new TunicUtils file, since it felt weird calling them from ItemRandomizer
> Make it so fairy seeking spell can pay attention to logic

- src/Patches/SceneLoaderPatches.cs
- src/Patches/TunicPortals.cs
It's dangerous to jump off ledges, little fox!
> Zig skip leads to above zig skip in ER now

- src/Data/Check.cs
- src/Data/SaveFlags.cs
- src/Patches/FairyTargets.cs
- src/Patches/GrassRandomizer.cs
- src/Patches/ItemRandomizer.cs
oh and also start with sword in logic
> Fix seeking spell logic not looking at abilities

- TunicRandomizer.csproj
- src/Patches/QuickSettings.cs
- Add visual cursor to text fields when a user is actively editing them
- Enables cursor navigation in the field using arrow keys, and cursor-aware backspace and delete
- disables all keyboard control of main menu while editing text, restores control when no longer editing
- general restructuring and encapsulation of the text field logic to improve readability of GUI layout code and simplify re-use
> Improve text boxes in quick settings UI

- src/Patches/ERScripts.cs
It just more closely matches how it looks on the AP-side now.
> Rewrite ER in AP style to help make direction pairs work more often

- src/Util/TunicUtils.cs
Probably the simplest fix we've had
> Fix seeking spell ignoring hex quest pages

- src/Archipelago/ArchipelagoIntegration.cs
- src/Data/Check.cs
- src/Patches/FairyTargets.cs
- src/Patches/ItemPatches.cs
- src/Patches/OptionsGUIPatches.cs
- src/Patches/PlayerCharacterPatches.cs
- src/Patches/SceneLoaderPatches.cs
- src/Util/TunicUtils.cs
Making it more sane mostly.
Populate each check list and then choose which to look at.
I still need to test it some more though.
> Update seeking spell

- src/Data/ItemTracker.cs
- src/Patches/OptionsGUIPatches.cs
- src/TunicRandomizer.cs
Populates the connections you travel between as you play
> Add entrance tracker file

- src/Patches/ERData.cs
> Fix fortress grave entrance rule

- src/Archipelago/ArchipelagoIntegration.cs
- src/Patches/BreakableShuffle.cs
- src/Patches/ERScripts.cs
- src/Patches/FairyTargets.cs
- src/Patches/GrassRandomizer.cs
- src/Patches/ItemPatches.cs
Forgot to change this when we added decoupled, woops!
> Fix for fairy targets checking adjacent scenes

- src/Archipelago/ArchipelagoIntegration.cs
- src/Patches/BreakableShuffle.cs
- src/Patches/ERScripts.cs
- src/Patches/FairyTargets.cs
- src/Patches/GrassRandomizer.cs
- src/Patches/ItemPatches.cs
Reverts silent-destroyer/tunic-randomizer#107
> Revert "Fix for fairy targets checking adjacent scenes"

- src/Patches/GhostHints.cs
- src/Patches/InteractionPatches.cs
- src/Patches/SceneLoaderPatches.cs
Now lower zig is slightly more populated
> More ghost foxes

- src/Util/FoolTrap.cs
Basically just a simple trip, felt easy enough to add in.
> Add trap link support for bonk traps

- src/Patches/ERScripts.cs
Also made the comments a little better
> Fix ER stopping too early

- src/Patches/ERScripts.cs
we love silly little lists of strings that have no error checking
> Fix ER yet again

- src/Archipelago/ArchipelagoIntegration.cs
- src/Util/FoolTrap.cs
Also refactored it so it won't get missed next time
> TrapLink: Fix Zoom traps not sending

- src/Util/FoolTrap.cs
Make it so if you have the zoom trap already active that it won't give it to you again
> Don't dupe zoom traps

- src/Patches/ModelSwaps.cs
Now when you break stuff, the color should stay the same
> Fix up debris colors
